export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const QUESTION_SELECTED = 'QUESTION_SELECTED';
export const QUESTION_VALUE_CHANGED = 'QUESTION_VALUE_CHANGED';
export const OPTION_VALUE_CHANGED = 'OPTION_VALUE_CHANGED';
export const ADD_OPTION_TO_QUESTION = 'ADD_OPTION_TO_QUESTION';
export const DELETE_OPTION_FROM_QUESTION = 'DELETE_OPTION_FROM_QUESTION';
export const UPDATE_QUESTION_IMAGE = 'UPDATE_QUESTION_IMAGE';
