export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const SELECT_QUESTION = 'SELECT_QUESTION';
export const UPDATE_QUESTION_VALUE = 'UPDATE_QUESTION_VALUE';
export const UPDATE_QUESTION_IMAGE = 'UPDATE_QUESTION_IMAGE';
export const UPDATE_OPTION_VALUE = 'UPDATE_OPTION_VALUE';
export const ADD_OPTION = 'ADD_OPTION';
export const DELETE_OPTION = 'DELETE_OPTION';
